#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${ROOT_DIR}/scripts/common.sh"

FREECIV_GENERATED_MAP="${FREECIV_GENERATED_MAP:-1}"
if [ "${FREECIV_GENERATED_MAP}" = "1" ]; then
  SERVER_RC="${SERVER_RC:-${ROOT_DIR}/start_generated_32x32.serv}"
  MAP_WIDTH="${MAP_WIDTH:-${FREECIV_MAP_W:-32}}"
  MAP_HEIGHT="${MAP_HEIGHT:-${FREECIV_MAP_H:-32}}"
else
  SERVER_RC="${SERVER_RC:-${ROOT_DIR}/start_single.serv}"
  MAP_WIDTH="${MAP_WIDTH:-${FREECIV_MAP_W:-16}}"
  MAP_HEIGHT="${MAP_HEIGHT:-${FREECIV_MAP_H:-16}}"
fi
if server_rc_has_start "${SERVER_RC}"; then
  FREECIV_TAKE_PLAYER="${FREECIV_TAKE_PLAYER:-}"
  FREECIV_START_AFTER_TAKE="${FREECIV_START_AFTER_TAKE:-0}"
else
  FREECIV_TAKE_PLAYER="${FREECIV_TAKE_PLAYER:-}"
  FREECIV_START_AFTER_TAKE="${FREECIV_START_AFTER_TAKE:-1}"
fi
FREECIV_START_COMMAND="${FREECIV_START_COMMAND:-}"
SERVER_PORT="${SERVER_PORT:-5566}"
LUA_PORT="${LUA_PORT:-4451}"
DISPLAY_NUM="${DISPLAY_NUM:-:101}"
TRAINING_STEPS="${TRAINING_STEPS:-5000}"
NUM_WORKERS="${NUM_WORKERS:-1}"
NUM_SIMULATIONS="${NUM_SIMULATIONS:-2}"
MAX_TURNS="${MAX_TURNS:-300}"
MAX_ACTIONS_PER_TURN="${MAX_ACTIONS_PER_TURN:-${FREECIV_MAX_ACTIONS_PER_TURN:-}}"
TRAINING_DELAY="${TRAINING_DELAY:-0.1}"
FREECIV_SLEEP="${FREECIV_SLEEP:-0.2}"
FREECIV_MAX_UNITS="${FREECIV_MAX_UNITS:-}"
FREECIV_MAX_CITIES="${FREECIV_MAX_CITIES:-}"
CHECKPOINT_PATH="${CHECKPOINT_PATH:-}"
REPLAY_BUFFER_PATH="${REPLAY_BUFFER_PATH:-}"
FREECIV_REWARD_EXPLORE="${FREECIV_REWARD_EXPLORE:-3.0}"
FREECIV_REWARD_CIV_SCORE="${FREECIV_REWARD_CIV_SCORE:-0.5}"
FREECIV_REWARD_CITY="${FREECIV_REWARD_CITY:-80.0}"
FREECIV_REWARD_POPULATION="${FREECIV_REWARD_POPULATION:-3.0}"
FREECIV_REWARD_SETTLER="${FREECIV_REWARD_SETTLER:-25.0}"
FREECIV_REWARD_POTENTIAL="${FREECIV_REWARD_POTENTIAL:-0.2}"
FREECIV_REWARD_POTENTIAL_DISCOUNT="${FREECIV_REWARD_POTENTIAL_DISCOUNT:-1.0}"
FREECIV_REWARD_TENSORBOARD="${FREECIV_REWARD_TENSORBOARD:-1}"
FREECIV_BELIEF_TENSORBOARD="${FREECIV_BELIEF_TENSORBOARD:-1}"
FREECIV_BELIEF_TENSORBOARD_INTERVAL="${FREECIV_BELIEF_TENSORBOARD_INTERVAL:-5}"
FREECIV_OBSERVE_BELIEF="${FREECIV_OBSERVE_BELIEF:-1}"
FREECIV_SERVER_PORT_STRIDE="${FREECIV_SERVER_PORT_STRIDE:-1}"
FREECIV_LUAREMOTE_PORT_STRIDE="${FREECIV_LUAREMOTE_PORT_STRIDE:-1}"
USE_GPU="${USE_GPU:-1}"
MUZERO_MAX_NUM_GPUS="${MUZERO_MAX_NUM_GPUS:-}"
MUZERO_SELFPLAY_ON_GPU="${MUZERO_SELFPLAY_ON_GPU:-true}"
MUZERO_TRAIN_ON_GPU="${MUZERO_TRAIN_ON_GPU:-true}"
MUZERO_REANALYSE_ON_GPU="${MUZERO_REANALYSE_ON_GPU:-true}"
MUZERO_BATCH_SIZE="${MUZERO_BATCH_SIZE:-128}"
MUZERO_CHANNELS="${MUZERO_CHANNELS:-32}"
MUZERO_BLOCKS="${MUZERO_BLOCKS:-2}"
MUZERO_NUM_UNROLL_STEPS="${MUZERO_NUM_UNROLL_STEPS:-20}"
XVFB_PATTERN="Xvfb ${DISPLAY_NUM}"

BUILD_DIR="${BUILD_DIR:-$(default_build_dir)}"
SCENARIO_PATH="${SCENARIO_PATH:-$(default_scenario_path)}"
FREECIV_SCORE_RUN_ID="${FREECIV_SCORE_RUN_ID:-$(date +%Y%m%d-%H%M%S)-$$}"
SERVER_RC_DIR="${SERVER_RC_DIR:-/tmp/freeciv-muzero-rc-${FREECIV_SCORE_RUN_ID}}"
SERVER_RC_COUNT="${NUM_WORKERS}"
if [ "${MUZERO_ENABLE_LIVE_TEST_WORKER:-0}" = "1" ]; then
  SERVER_RC_COUNT=$((SERVER_RC_COUNT + 1))
fi
SERVER_RC_TEMPLATE="$(prepare_server_rc_template \
  "${SERVER_RC}" \
  "${SERVER_RC_DIR}" \
  "${SERVER_PORT}" \
  "${FREECIV_SERVER_PORT_STRIDE}" \
  "${SERVER_RC_COUNT}" \
  "${FREECIV_SCORE_RUN_ID}")"
if [ "${FREECIV_GENERATED_MAP}" = "1" ]; then
  FREECIV_SERVER_CMD_TEMPLATE="${BUILD_DIR}/run.sh freeciv-server -p {server_port} -r ${SERVER_RC_TEMPLATE}"
else
  FREECIV_SERVER_CMD_TEMPLATE="${BUILD_DIR}/run.sh freeciv-server -p {server_port} -f ${SCENARIO_PATH} -r ${SERVER_RC_TEMPLATE}"
fi

if [ "${USE_GPU}" = "0" ]; then
  MUZERO_MAX_NUM_GPUS=0
  MUZERO_SELFPLAY_ON_GPU=false
  MUZERO_TRAIN_ON_GPU=false
  MUZERO_REANALYSE_ON_GPU=false
else
  init_train_runtime train_headless
  MUZERO_MAX_NUM_GPUS="${MUZERO_MAX_NUM_GPUS:-1}"
fi

cleanup() {
  local extra_workers=0
  if [ "${MUZERO_ENABLE_LIVE_TEST_WORKER:-0}" = "1" ]; then
    extra_workers=1
  fi
  local total=$((NUM_WORKERS + extra_workers))
  local idx
  for ((idx = 0; idx < total; idx++)); do
    cleanup_freeciv_all \
      "$((SERVER_PORT + idx * FREECIV_SERVER_PORT_STRIDE))" \
      "$((LUA_PORT + idx * FREECIV_LUAREMOTE_PORT_STRIDE))" \
      "${DISPLAY_NUM}"
  done
  pkill -f "${XVFB_PATTERN}" >/dev/null 2>&1 || true
}

trap cleanup EXIT INT TERM

cleanup

Xvfb "${DISPLAY_NUM}" -screen 0 1280x800x24 -nolisten tcp >/tmp/freeciv-muzero-xvfb.log 2>&1 &
sleep 1
export DISPLAY="${DISPLAY_NUM}"

cd "${ROOT_DIR}"
init_python_env

run_with_timing_and_log train_headless python muzero.py freeciv_remote "{
  \"checkpoint_path\": \"${CHECKPOINT_PATH}\",
  \"replay_buffer_path\": \"${REPLAY_BUFFER_PATH}\",
  \"training_steps\": ${TRAINING_STEPS},
  \"num_workers\": ${NUM_WORKERS},
  \"num_simulations\": ${NUM_SIMULATIONS},
  \"max_turns\": ${MAX_TURNS},
  \"training_delay\": ${TRAINING_DELAY},
  \"max_num_gpus\": ${MUZERO_MAX_NUM_GPUS},
  \"selfplay_on_gpu\": ${MUZERO_SELFPLAY_ON_GPU},
  \"train_on_gpu\": ${MUZERO_TRAIN_ON_GPU},
  \"reanalyse_on_gpu\": ${MUZERO_REANALYSE_ON_GPU},
  \"train_gpu_id\": \"${MUZERO_TRAIN_GPU_ID:-}\",
  \"selfplay_gpu_ids\": \"${MUZERO_SELFPLAY_GPU_IDS:-}\",
  \"reanalyse_gpu_id\": \"${MUZERO_REANALYSE_GPU_ID:-}\",
  \"batch_size\": ${MUZERO_BATCH_SIZE},
  \"channels\": ${MUZERO_CHANNELS},
  \"blocks\": ${MUZERO_BLOCKS},
  \"num_unroll_steps\": ${MUZERO_NUM_UNROLL_STEPS},
  \"env\": {
    \"FREECIV_SERVER_PORT\": \"${SERVER_PORT}\",
    \"FREECIV_SERVER_PORT_STRIDE\": \"${FREECIV_SERVER_PORT_STRIDE}\",
    \"FREECIV_SERVER_CMD\": \"${FREECIV_SERVER_CMD_TEMPLATE}\",
    \"FREECIV_HOST\": \"127.0.0.1\",
    \"FREECIV_LUAREMOTE_PORT\": \"${LUA_PORT}\",
    \"FREECIV_LUAREMOTE_PORT_STRIDE\": \"${FREECIV_LUAREMOTE_PORT_STRIDE}\",
    \"FREECIV_CLIENT_CMD\": \"${BUILD_DIR}/run.sh freeciv-gtk3.22 -a -s 127.0.0.1 -p {server_port} -n agent0 -P none\",
    \"FREECIV_PLAYER_ID\": \"0\",
    \"FREECIV_TAKE_PLAYER_ID\": \"0\",
    \"FREECIV_TAKE_PLAYER\": \"${FREECIV_TAKE_PLAYER}\",
    \"FREECIV_START_AFTER_TAKE\": \"${FREECIV_START_AFTER_TAKE}\",
    \"FREECIV_START_COMMAND\": \"${FREECIV_START_COMMAND}\",
    \"FREECIV_MAP_W\": \"${MAP_WIDTH}\",
    \"FREECIV_MAP_H\": \"${MAP_HEIGHT}\",
    \"FREECIV_MAX_TURNS\": \"${MAX_TURNS}\",
    \"FREECIV_MAX_ACTIONS_PER_TURN\": \"${MAX_ACTIONS_PER_TURN}\",
    \"FREECIV_MAX_UNITS\": \"${FREECIV_MAX_UNITS}\",
    \"FREECIV_MAX_CITIES\": \"${FREECIV_MAX_CITIES}\",
    \"FREECIV_SLEEP\": \"${FREECIV_SLEEP}\",
    \"FREECIV_REWARD_EXPLORE\": \"${FREECIV_REWARD_EXPLORE}\",
    \"FREECIV_REWARD_CIV_SCORE\": \"${FREECIV_REWARD_CIV_SCORE}\",
    \"FREECIV_REWARD_CITY\": \"${FREECIV_REWARD_CITY}\",
    \"FREECIV_REWARD_POPULATION\": \"${FREECIV_REWARD_POPULATION}\",
    \"FREECIV_REWARD_SETTLER\": \"${FREECIV_REWARD_SETTLER}\",
    \"FREECIV_REWARD_POTENTIAL\": \"${FREECIV_REWARD_POTENTIAL}\",
    \"FREECIV_REWARD_POTENTIAL_DISCOUNT\": \"${FREECIV_REWARD_POTENTIAL_DISCOUNT}\",
    \"FREECIV_REWARD_TENSORBOARD\": \"${FREECIV_REWARD_TENSORBOARD}\",
    \"FREECIV_BELIEF_TENSORBOARD\": \"${FREECIV_BELIEF_TENSORBOARD}\",
    \"FREECIV_BELIEF_TENSORBOARD_INTERVAL\": \"${FREECIV_BELIEF_TENSORBOARD_INTERVAL}\",
    \"FREECIV_OBSERVE_BELIEF\": \"${FREECIV_OBSERVE_BELIEF}\"
  }
}"
